version: 2.0
jobs:

  unittests:
    working_directory: ~/repo
    docker:
    - image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          pip install -r test-requirements.txt
    - run:
        name: Run unit tests
        command: |
          export PYTHONPATH=${PYTHONPATH}:$(pwd)
          export ENV=test
          pytest tests/*.py

  deploy:
    working_directory: ~/repo
    docker:
    - image: google/cloud-sdk:265.0.0
    steps:
    - checkout
    - run:
        name: Create credentials file
        command: |
          mkdir credentials
          echo $CI_JSON_CREDENTIALS_PRODUCTION >> credentials/ci-production.json
    - run:
        name: Create environment variables file
        command: |
          mkdir env-vars
          echo $ENV_VARS_PRODUCTION >> env-vars/production.env
    - run:
        name: Authenticate gcloud
        command: |
          gcloud auth activate-service-account --key-file credentials/ci-production.json
    - run:
        name: Install Docker Client
        command: |
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          mv /tmp/docker/docker* /usr/bin/
    - run:
        name: Debug docker
        command: |
          docker version
    - run:
        name: Build docker image
        command: |
          gcloud auth configure-docker --quiet
          export DOCKER_TAG=gcr.io/${GCP_PROJECT_ID}/cnf-api-production:latest
          docker build . \
#            -t ${DOCKER_TAG} \
#            --build-arg config_file=production.ini


workflows:
  version: 2
  test-build-deploy:
    jobs:
    - unittests:
        filters:
          branches:
            ignore:
            - master

    - deploy:
        filters:
          branches:
            ignore:
            - master
